import json
import os
HERE=os.path.dirname(os.path.abspath(__file__))
g=json.load(open(os.path.join(HERE,'graph.json')))
TAXI={20,25,66}
PTR={'harney_jones_shack':[9],'train_station':[1],'black_cave':[8],'silver_twilight_lodge':[13],
'lake_miskatonic':[16],'miskatonic_u':[23,38],'north_church':[24],'shunned_house':[19],'woods':[22],
'graveyard':[34],'city_hall':[36],'boarding_house':[30,51],'police_station':[39],'velmas_diner':[44],
'dagon_mission':[43,65],'hospital':[46],'sanitarium':[47],'newspaper':[48],'library':[59],
'devils_beach':[68],'historical_society':[67],'darks_carnival':[62],'curiositie_shoppe':[64],
'lighthouse':[60],'hibs_roadhouse':[50],'founders_rock':[52]}
LOC={'harney_jones_shack':(1030,630),'train_station':(1930,601),'black_cave':(2635,610),
'silver_twilight_lodge':(3055,690),'lake_miskatonic':(2925,1080),'miskatonic_u':(2775,1280),
'north_church':(2515,970),'shunned_house':(1995,850),'woods':(1470,940),'graveyard':(1240,1180),
'city_hall':(2075,1260),'hospital':(1310,1560),'sanitarium':(1570,1570),'newspaper':(830,1640),
'library':(1220,1970),'historical_society':(1540,1960),'dagon_mission':(1880,1970),
'devils_beach':(1320,2270),'police_station':(2025,1590),'velmas_diner':(2135,1700),
'boarding_house':(2395,1650),'founders_rock':(2675,1700),'hibs_roadhouse':(3095,1640),
'curiositie_shoppe':(2875,1960),'lighthouse':(3145,2140),'darks_carnival':(2125,2250)}
ptrs={s:l for l,ss in PTR.items() for s in ss}
out=[]
out.append('// Generated by tools/genboard.py from the board scan segmentation. Coordinates are pixels on public/assets/board.jpg (3508x2480).')
out.append("import type { LocationId } from './effects';\n")
out.append("export interface Space { id: string; x: number; y: number; taxi?: boolean; pointsTo?: LocationId; poly: [number, number][] }")
out.append("export const BOARD_W = 3508;\nexport const BOARD_H = 2480;\n")
out.append('export const SPACES: Record<string, Space> = {')
for k in sorted(g['spaces'],key=int):
  s=g['spaces'][k]; extra=''
  if int(k) in TAXI: extra+=', taxi: true'
  if int(k) in ptrs: extra+=f", pointsTo: '{ptrs[int(k)]}'"
  out.append(f"  s{k}: {{ id: 's{k}', x: {s['x']}, y: {s['y']}{extra}, poly: {json.dumps(s['poly'],separators=(',',':'))} }},")
out.append('};\n')
out.append('/** Street-to-street connections. */')
out.append('export const STREET_EDGES: [string, string][] = [')
out.append('  '+', '.join(f"['s{a}', 's{b}']" for a,b in g['edges'])+',')
out.append('];\n')
out.append('/** Location art anchor and the street spaces its pointers mark (entrances). */')
out.append('export const LOCATION_NODES: Record<LocationId, { x: number; y: number; entrances: string[] }> = {')
for l,(x,y) in LOC.items():
  out.append(f"  {l}: {{ x: {x}, y: {y}, entrances: [{', '.join(repr('s'+str(s)) for s in PTR[l])}] }},")
out.append('};')
open(os.path.join(HERE,'..','src','engine','data','boardData.ts'),'w').write('\n'.join(out)+'\n')
